### ISSUE TITLE
remove astring dependency

### ISSUE THREAD

**Issue by verbosemode** [hannesm/logs-syslog#16]
I'm just leaving this here as a reminder that we need to find a replacement for [Astring.String.take](https://github.com/hannesm/logs-syslog/blob/d9fc2c04686e3ae922a42fa3fa910864f9f928d1/src/logs_syslog.ml#L37) :smiley:

syslog-message 1.2.0 is dropping Astring as dependency.

* [new release] syslog-message (1.2.0) [#23870](https://github.com/ocaml/opam-repository/pull/23870)
* add upper bounds to logs-syslog due to new syslog-message release 1.2.0 [23871](https://github.com/ocaml/opam-repository/pull/23871)

**Comment by hannesm** [comment]
thanks for your issue, this is done in https://github.com/hannesm/logs-syslog/commit/5f060db27d26cdd0e09e1cfdb139cdd098f137ab (part of https://github.com/ocaml/opam-repository/pull/23875)
