### ISSUE TITLE
Specify the facility

### ISSUE THREAD

**Issue by dra27** [hannesm/logs-syslog#7]
There is a TODO comment in [logs_syslog.ml](https://github.com/hannesm/logs-syslog/blob/master/src/logs_syslog.ml#L18) which I'd like to address!

Currently the log messages are always written to facility 3 (daemon). I can see various options for changing this, but wonder what you think before doing any of them:

 1. Simply add `?facility` to each reporter function
 2. Have a global map between `Logs.src` and `Syslog_message.facility`
 3. Have a global `Syslog_message.facility Logs.Tag.def` which can be attached to any message

1 probably covers virtually all use-cases, since most applications will surely only ever write to one facility (I'm not certain that statement is true). 2 seems to carry a risk of either race-conditions, ugliness, or stacking problems if you are also allowed to *change* the map. Conversely, the API looks ugly if you make it that the facility can only be set once.

My feeling is that 1 and 3 is probably the way to do it? So have `Logs_syslog.facility_tag` which can be used with any message and is intended to control the facility with a fallback to whatever was given in the `?facility` argument of the specific reporter?

**Comment by hannesm** [comment]
yeah, I briefly thought about (2) while implementing it, and it felt too ugly. (3) sounds sensible for me, and (1) pragmatic.  in a MirageOS setting, I actually would like to be able to specify different facilities via a single reporter! :)
